<?xml version="1.0"?>
<!DOCTYPE student [
        <!ELEMENT student (id,name,male,age)>
        <!ELEMENT id      (#PCDATA)>
        <!ELEMENT name    (#PCDATA)>
        <!ELEMENT male (#PCDATA)>
        <!ELEMENT age    (#PCDATA)>
        ]>

<!--

!DOCTYPE student (第二行)定义此文档是 student 类型的文档。
!ELEMENT student (第三行)定义 student 元素有四个元素："id、name、male,、age"
!ELEMENT id (第四行)定义 id 元素为 "#PCDATA" 类型  ==> PCDATA : parsed character data 被解析的字符串数据
!ELEMENT name (第五行)定义 name 元素为 "#PCDATA" 类型
!ELEMENT male (第六行)定义 male 元素为 "#PCDATA" 类型
!ELEMENT age (第七行)定义 age 元素为 "#PCDATA" 类型

FAQ: 为什么使用 DTD？
通过 DTD，您的每一个 XML 文件均可携带一个有关其自身格式的描述。
通过 DTD，独立的团体可一致地使用某个标准的 DTD 来交换数据。
而您的应用程序也可使用某个标准的 DTD 来验证从外部接收到的数据。
还可以使用 DTD 来验证您自身的数据。 ===> 关于如何验证，参考test包下面的代码

更多参考:
@see http://www.w3school.com.cn/dtd/index.asp

-->
<!--
按住你的control键，鼠标移动到"student, id, name"等元素上的时候，他会自动定位到dtd的定义
 -->

<student>
    <id>1</id>
    <name>yushen.ma</name>
    <male>boy</male>
    <age>23</age>
</student>

